name: Feature Request
description: Suggest an idea for this script
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What's the use case or pain point?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should it work?
    validations:
      required: true
